development:
 adapter: postgresql
 encoding: unicode
 database: timetracking_development
 pool: 5
 username: diana
 password: 123456

test:
 adapter: postgresql
 encoding: unicode
 database: timetracking_test
 pool: 5
 username: diana
 password: 123456

production:
 adapter: postgresql
 encoding: unicode
 database: timetracking_production
 pool: 5
 username: diana
 password: 123456 